# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_definition.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_definition.proto',
  package='payment',
  syntax='proto3',
  serialized_pb=_b('\n\x18service_definition.proto\x12\x07payment\",\n\x17GetPaymentStatusRequest\x12\x11\n\treference\x18\x01 \x01(\t\"*\n\x18GetPaymentStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\";\n\x0fGetTokenRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x16\n\x0epayment_amount\x18\x02 \x01(\x02\")\n\x10GetTokenResponse\x12\x15\n\rpayment_token\x18\x01 \x01(\t2\xae\x01\n\x0ePaymentService\x12Y\n\x10GetPaymentStatus\x12 .payment.GetPaymentStatusRequest\x1a!.payment.GetPaymentStatusResponse\"\x00\x12\x41\n\x08GetToken\x12\x18.payment.GetTokenRequest\x1a\x19.payment.GetTokenResponse\"\x00\x62\x06proto3')
)




_GETPAYMENTSTATUSREQUEST = _descriptor.Descriptor(
  name='GetPaymentStatusRequest',
  full_name='payment.GetPaymentStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reference', full_name='payment.GetPaymentStatusRequest.reference', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=81,
)


_GETPAYMENTSTATUSRESPONSE = _descriptor.Descriptor(
  name='GetPaymentStatusResponse',
  full_name='payment.GetPaymentStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='payment.GetPaymentStatusResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=125,
)


_GETTOKENREQUEST = _descriptor.Descriptor(
  name='GetTokenRequest',
  full_name='payment.GetTokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='payment.GetTokenRequest.order_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payment_amount', full_name='payment.GetTokenRequest.payment_amount', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=186,
)


_GETTOKENRESPONSE = _descriptor.Descriptor(
  name='GetTokenResponse',
  full_name='payment.GetTokenResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payment_token', full_name='payment.GetTokenResponse.payment_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=229,
)

DESCRIPTOR.message_types_by_name['GetPaymentStatusRequest'] = _GETPAYMENTSTATUSREQUEST
DESCRIPTOR.message_types_by_name['GetPaymentStatusResponse'] = _GETPAYMENTSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['GetTokenRequest'] = _GETTOKENREQUEST
DESCRIPTOR.message_types_by_name['GetTokenResponse'] = _GETTOKENRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetPaymentStatusRequest = _reflection.GeneratedProtocolMessageType('GetPaymentStatusRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPAYMENTSTATUSREQUEST,
  __module__ = 'service_definition_pb2'
  # @@protoc_insertion_point(class_scope:payment.GetPaymentStatusRequest)
  ))
_sym_db.RegisterMessage(GetPaymentStatusRequest)

GetPaymentStatusResponse = _reflection.GeneratedProtocolMessageType('GetPaymentStatusResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETPAYMENTSTATUSRESPONSE,
  __module__ = 'service_definition_pb2'
  # @@protoc_insertion_point(class_scope:payment.GetPaymentStatusResponse)
  ))
_sym_db.RegisterMessage(GetPaymentStatusResponse)

GetTokenRequest = _reflection.GeneratedProtocolMessageType('GetTokenRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETTOKENREQUEST,
  __module__ = 'service_definition_pb2'
  # @@protoc_insertion_point(class_scope:payment.GetTokenRequest)
  ))
_sym_db.RegisterMessage(GetTokenRequest)

GetTokenResponse = _reflection.GeneratedProtocolMessageType('GetTokenResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETTOKENRESPONSE,
  __module__ = 'service_definition_pb2'
  # @@protoc_insertion_point(class_scope:payment.GetTokenResponse)
  ))
_sym_db.RegisterMessage(GetTokenResponse)



_PAYMENTSERVICE = _descriptor.ServiceDescriptor(
  name='PaymentService',
  full_name='payment.PaymentService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=232,
  serialized_end=406,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPaymentStatus',
    full_name='payment.PaymentService.GetPaymentStatus',
    index=0,
    containing_service=None,
    input_type=_GETPAYMENTSTATUSREQUEST,
    output_type=_GETPAYMENTSTATUSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetToken',
    full_name='payment.PaymentService.GetToken',
    index=1,
    containing_service=None,
    input_type=_GETTOKENREQUEST,
    output_type=_GETTOKENRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PAYMENTSERVICE)

DESCRIPTOR.services_by_name['PaymentService'] = _PAYMENTSERVICE

# @@protoc_insertion_point(module_scope)
