# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import test_service.generated_interfaces.service_definition_pb2 as service__definition__pb2


class PaymentServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPaymentStatus = channel.unary_unary(
        '/payment.PaymentService/GetPaymentStatus',
        request_serializer=service__definition__pb2.GetPaymentStatusRequest.SerializeToString,
        response_deserializer=service__definition__pb2.GetPaymentStatusResponse.FromString,
        )
    self.GetToken = channel.unary_unary(
        '/payment.PaymentService/GetToken',
        request_serializer=service__definition__pb2.GetTokenRequest.SerializeToString,
        response_deserializer=service__definition__pb2.GetTokenResponse.FromString,
        )


class PaymentServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPaymentStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPaymentStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetPaymentStatus,
          request_deserializer=service__definition__pb2.GetPaymentStatusRequest.FromString,
          response_serializer=service__definition__pb2.GetPaymentStatusResponse.SerializeToString,
      ),
      'GetToken': grpc.unary_unary_rpc_method_handler(
          servicer.GetToken,
          request_deserializer=service__definition__pb2.GetTokenRequest.FromString,
          response_serializer=service__definition__pb2.GetTokenResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'payment.PaymentService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
