apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    app: {{ include "charts.name" . }}
    chart: {{ include "charts.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: {{ include "charts.name" . }}
    release: {{ .Release.Name }}
